---
title: "Data Gathering"
author: "Mitch Lueken"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: html_document
---

```{r setup, echo = FALSE, message = FALSE}
library(tidyverse)
library(HelpersMG)
library(lubridate)
library(ggplot2)
library(kableExtra)
library(readxl)
library(haven)
```

```{r gimmeData, echo = FALSE, message = FALSE}
if(!file.exists("./raw_data/States-Cases.tsv")) {
  wget(url = "https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/HIDLTK/ROCWVZ", destfile = "./raw_data/States-Cases.tsv")
}

if(!file.exists("./raw_data/States-Deaths.tsv")) {
  wget(url = "https://dataverse.harvard.edu/api/access/datafile/:persistentId?persistentId=doi:10.7910/DVN/HIDLTK/DOK6EK", destfile = "./raw_data/States-Deaths.tsv")
}

if(!file.exists("./raw_data/States-Votes.xlsx")) {
  wget(url = "https://www.fec.gov/documents/1890/federalelections2016.xlsx", destfile = "./raw_data/States-Votes.xlsx", compression=none) # Gives corrupted file for some reason, manual download works fine
}

if(!file.exists("./raw_data/States-Governors.csv")) {
  wget(url = "https://github.com/luekenm/COVID-19/raw_data/States-Governors.csv", destfile = "./raw_data/States-Governors.csv")
}

if(!file.exists("./raw_data/LLCP2018.XPT")) {
  wget(url = "https://www.cdc.gov/brfss/annual_data/2018/files/LLCP2018XPT.zip", destfile = "./raw_data/LLCP2018XPT.zip")
  unzip("./raw_data/LLCP2018XPT.zip", exdir = "./raw_data")
  unlink("./raw_data/LLCP2018XPT.zip")
}

if(!file.exists("./raw_data/Dataset - Pew Research Center 2014 Religious Landscape Study National Telephone Survey - Version 1.1 - December 1 2016.sav")) {
  wget(url = "https://www.pewforum.org/wp-content/uploads/sites/7/2016/12/Pew-Research-Center-2014-U.S.-Religious-Landscape-Study.zip", destfile = "./raw_data/Pew-Research-Center-2014-U.S.-Religious-Landscape-Study.zip")
  unzip("./raw_data/Pew-Research-Center-2014-U.S.-Religious-Landscape-Study.zip", exdir = "./raw_data")
  unlink("./raw_data/Pew-Research-Center-2014-U.S.-Religious-Landscape-Study.zip")
  unlink("./raw_data/Codebook - Pew Research Center 2014 Religious Landscape Study National Telephone Survey - Version 1.1 - December 1 2016.pdf")
}

if(!file.exists("./raw_data/States-WholeFoods.csv")) {
  wget(url = "https://github.com/luekenm/COVID-19/raw_data/States-WholeFoods.csv", destfile = "./raw_data/States-WholeFoods.csv")
}

if(!file.exists("./raw_data/Whose Heritage SF - Symbol Type Count by State.csv")) {
  wget(url = "https://docs.google.com/spreadsheets/d/1W4H2qa2THM1ni53QYZftGob_k_Bf9HreFAtCERfjCIU/export?format=csv&id=1W4H2qa2THM1ni53QYZftGob_k_Bf9HreFAtCERfjCIU&gid=534759525", destfile = "./raw_data/Whose Heritage SF - Symbol Type Count by State.csv")
}
```

```{r covidData, echo = FALSE, message = FALSE}
dateButchery <- function(date) {
	return(mdy(paste(substr(date, 6, 7), "-", substr(date, 9, 10), "-", substr(date, 1, 4))))
}

tally <- function(column) {
  index = 1
	for(element in column) {
	  if(index > 1) {
        if(column[[index]] - column[[index - 1]] < 0) { # No negatives
          column[[index]] = 0
      } else {
          column[[index]] = column[[index]] - column[[index - 1]]
      }
    }
	    index = index + 1
  }
  	return(column)
}

cases <- read_tsv("./raw_data/States-Cases.tsv") %>%
  select(-c(fips, POP70, HHD70, POP80, HHD80, POP90, HHD90, POP00, HHD00, POP10, HHD10)) %>%
	pivot_longer(-NAME,
				 names_to = "Date",
				 values_to = "Total_Cases") %>%
	mutate(Date = dateButchery(Date))

read_tsv("./raw_data/States-Deaths.tsv") %>%
  select(-c(fips, POP70, HHD70, POP80, HHD80, POP90, HHD90, POP00, HHD00, HHD10)) %>%
	pivot_longer(-c(NAME, POP10),
				 names_to = "Date",
				 values_to = "Total_Deaths") %>%
	rename(Population = POP10) %>%
	mutate(Date = dateButchery(Date)) %>%
  right_join(cases, by = c("NAME", "Date")) %>%
  rename(State = NAME) %>%
  mutate(Daily_Cases = tally(Total_Cases),
         Daily_Deaths = tally(Total_Deaths),
         Per_Capita_Total_Cases = Total_Cases / Population,
         Per_Capita_Total_Deaths = Total_Deaths / Population,
         Per_Capita_Daily_Cases = Daily_Cases / Population,
         Per_Capita_Daily_Deaths = Daily_Deaths / Population) %>%
	write.table(file = "./output/States_COVID_data_by_date.csv", row.names = FALSE, sep = ",")
```

```{r electionData, echo = FALSE, message = FALSE}
margin <- function(trump, clinton) {
  index = 1
  for(votes in trump) {
    trump[[index]] = (trump[[index]] - clinton[[index]]) / (trump[[index]] + clinton[[index]])
    index = index + 1
  }
  return(trump)
}

read_excel("./raw_data/States-Votes.xlsx", sheet = "Table 2. Electoral &  Pop Vote") %>%
  select(1, 4, 5) %>%
  rename(State = 1, Trump = 2, Clinton = 3) %>%
  slice(4:54) %>%
  mutate(Trump = as.numeric(Trump), Clinton = as.numeric(Clinton)) %>%
  mutate(Margin = margin(Trump, Clinton)) %>%
  full_join(read_csv("./raw_data/States-Governors.csv"), by = "State") %>%
  write.table(file = "./output/States_info.csv", row.names = FALSE, sep = ",")
```

```{r healthData, echo = FALSE}
fipsTranslator <- function(column) {
  index = 1
  for(integer in column) {
    if(integer == 01) {
      column[[index]]="AL"
    } else if(integer == 02) {
      column[[index]]="AK"
    } else if(integer == 04) {
      column[[index]]="AZ"
    } else if(integer == 05) {
     column[[index]]="AR"
    } else if(integer == 06) {
      column[[index]]="CA"
    } else if(integer == 08) {
      column[[index]]="CO"
    } else if(integer == 09) {
      column[[index]]="CT"
    } else if(integer == 10) {
      column[[index]]="DE"
    } else if(integer == 11) {
      column[[index]]="DC"
    } else if(integer == 12) {
      column[[index]]="FL"
    } else if(integer == 13) {
      column[[index]]="GA"
    } else if(integer == 15) {
      column[[index]]="HI"
    } else if(integer == 16) {
      column[[index]]="ID"
    } else if(integer == 17) {
      column[[index]]="IL"
    } else if(integer == 18) {
      column[[index]]="IN"
    } else if(integer == 19) {
      column[[index]]="IA"
    } else if(integer == 20) {
      column[[index]]="KS"
    } else if(integer == 21) {
      column[[index]]="KY"
    } else if(integer == 22) {
      column[[index]]="LA"
    } else if(integer == 23) {
      column[[index]]="ME"
    } else if(integer == 24) {
      column[[index]]="MD"
    } else if(integer == 25) {
      column[[index]]="MA"
    } else if(integer == 26) {
      column[[index]]="MI"
    } else if(integer == 27) {
      column[[index]]="MN"
    } else if(integer == 28) {
      column[[index]]="MS"
    } else if(integer == 29) {
      column[[index]]="MO"
    } else if(integer == 30) {
      column[[index]]="MT"
    } else if(integer == 31) {
      column[[index]]="NE"
    } else if(integer == 32) {
      column[[index]]="NV"
    } else if(integer == 33) {
      column[[index]]="NH"
    } else if(integer == 34) {
      column[[index]]="NJ"
    } else if(integer == 35) {
      column[[index]]="NM"
    } else if(integer == 36) {
      column[[index]]="NY"
    } else if(integer == 37) {
      column[[index]]="NC"
    } else if(integer == 38) {
      column[[index]]="ND"
    } else if(integer == 39) {
      column[[index]]="OH"
    } else if(integer == 40) {
      column[[index]]="OK"
    } else if(integer == 41) {
      column[[index]]="OR"
    } else if(integer == 42) {
      column[[index]]="PA"
    } else if(integer == 44) {
      column[[index]]="RI"
    } else if(integer == 45) {
      column[[index]]="SC"
    } else if(integer == 46) {
      column[[index]]="SD"
    } else if(integer == 47) {
      column[[index]]="TN"
    } else if(integer == 48) {
      column[[index]]="TX"
    } else if(integer == 49) {
      column[[index]]="UT"
    } else if(integer == 50) {
      column[[index]]="VT"
    } else if(integer == 51) {
      column[[index]]="VA"
    } else if(integer == 53) {
      column[[index]]="WA"
    } else if(integer == 54) {
      column[[index]]="WV"
    } else if(integer == 55) {
      column[[index]]="WI"
    } else if(integer == 56) {
      column[[index]]="WY"
    } else {
      column[[index]]="NA"
    }
    index = index + 1
  }
  return(column)
}

read_xpt("./raw_data/LLCP2018.XPT") %>%
  mutate(State = fipsTranslator(`_STATE`)) %>%
  filter(!State == "NA") %>%
  filter(STATERE1 == 1) %>%
  select(c(28:31,34:41,45,48:50,53,64,65,73,79,81:85,88,89,112,129,147,148,149,248,276)) %>% # Should also use weighting
  write.table(file = "./output/States_health.csv", row.names = FALSE, sep = ",")
```

```{r healthComputations, echo = FALSE, message = FALSE, warning = FALSE}
states_health <- read_csv("./output/States_health.csv")
computedStatesHealth <- states_health %>%
  filter(GENHLTH > 0) %>%
  filter(GENHLTH < 6) %>%
  group_by(State) %>%
  summarize(General_Health = mean(GENHLTH)) %>%
  arrange(desc(General_Health)) # 1-5; General Health: 1 Excellent, 5 Poor

recodeHLTH <- function(column) {
  index = 1
  for(element in column) {
    if(element == 88) {
      column[[index]] = 0
    }
    index = index + 1
  }
  return(column)
}

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(PHYSHLTH > 0) %>%
  filter(PHYSHLTH < 89) %>%
  mutate(PHYSHLTH = recodeHLTH(PHYSHLTH)) %>%
  summarize(Physical_Health = mean(PHYSHLTH)) %>% # 0-30; Physical Health: Average days in last month that physical health was not good
  right_join(computedStatesHealth, by = "State")

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(MENTHLTH > 0) %>%
  filter(MENTHLTH < 89) %>%
  mutate(MENTHLTH = recodeHLTH(MENTHLTH)) %>%
  summarize(Mental_Health = mean(MENTHLTH)) %>% # 0-30; Mental Health: Average days in last month that mental health was not good
  right_join(computedStatesHealth, by = "State")

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(POORHLTH > 0) %>%
  filter(POORHLTH < 89) %>%
  mutate(POORHLTH = recodeHLTH(POORHLTH)) %>%
  summarize(Poor_Health = mean(POORHLTH)) %>% # 0-30; Poor Health: Average days in last month that poor health interferred with ADL
  right_join(computedStatesHealth, by = "State")

recodeBool <- function(column) {
  index = 1
  for(element in column) {
    if(element == 2) {
      column[[index]] = 0
    }
    index = index + 1
  }
  return(column)
}

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(MEDCOST > 0) %>%
  filter(MEDCOST < 3) %>%
  mutate(MEDCOST = recodeBool(MEDCOST)) %>%
  summarize(Medical_Cost = mean(MEDCOST)) %>% # 0-1; Prohibitive Medical Cost: Proportion of state that was unable to see doctor in past year when needed due to cost of health care
  right_join(computedStatesHealth, by = "State")

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(EXERANY2 > 0) %>%
  filter(EXERANY2 < 3) %>%
  mutate(EXERANY2 = recodeBool(EXERANY2)) %>%
  summarize(Exercise = mean(EXERANY2)) %>% # 0-1; Exercise: Proportion of state that exercised at all in last month
  right_join(computedStatesHealth, by = "State")

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(CVDINFR4 > 0) %>%
  filter(CVDINFR4 < 3) %>%
  mutate(CVDINFR4 = recodeBool(CVDINFR4)) %>%
  summarize(Heart_Attack = mean(CVDINFR4)) %>% # 0-1; Heart Attack: Proportion of state that has ever had a heart attack
  right_join(computedStatesHealth, by = "State")

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(CVDCRHD4 > 0) %>%
  filter(CVDCRHD4 < 3) %>%
  mutate(CVDCRHD4 = recodeBool(CVDCRHD4)) %>%
  summarize(Heart_Disease = mean(CVDCRHD4)) %>% # 0-1; Heart Disease: Proportion of state with angina or coronary heart disease
  right_join(computedStatesHealth, by = "State")

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(CVDSTRK3 > 0) %>%
  filter(CVDSTRK3 < 3) %>%
  mutate(CVDSTRK3 = recodeBool(CVDSTRK3)) %>%
  summarize(Stroke = mean(CVDSTRK3)) %>% # 0-1; Stroke: Proportion of state that has ever had a stroke
  right_join(computedStatesHealth, by = "State")

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(ASTHMA3 > 0) %>%
  filter(ASTHMA3 < 3) %>%
  mutate(ASTHMA3 = recodeBool(ASTHMA3)) %>%
  summarize(Asthma = mean(ASTHMA3)) %>% # 0-1; Asthma: Proportion of state that has ever had asthma
  right_join(computedStatesHealth, by = "State")

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(CHCCOPD1 > 0) %>%
  filter(CHCCOPD1 < 3) %>%
  mutate(CHCCOPD1 = recodeBool(CHCCOPD1)) %>%
  summarize(COPD = mean(CHCCOPD1)) %>% # 0-1; COPD: Proportion of state that has ever had Chronic Obstructive Pulminary Disease
  right_join(computedStatesHealth, by = "State")

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(CHCKDNY1 > 0) %>%
  filter(CHCKDNY1 < 3) %>%
  mutate(CHCKDNY1 = recodeBool(CHCKDNY1)) %>%
  summarize(Kidney_Disease = mean(CHCKDNY1)) %>% # 0-1; Kidney Disease: Proportion of state that has ever had Kidney Disease
  right_join(computedStatesHealth, by = "State")

recodeDiabetes <- function(column) {
  index = 1
  for(element in column) {
    if(element == 2) {
      column[[index]] = 0
    } else if(element == 3) {
      column[[index]] = 0
    } else if(element == 4) {
      column[[index]] = 1
    }
    index = index + 1
  }
  return(column)
}

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(DIABETE3 > 0) %>%
  filter(DIABETE3 < 5) %>%
  mutate(DIABETE3 = recodeDiabetes(DIABETE3)) %>%
  summarize(Diabetes = mean(DIABETE3)) %>% # 0-1; Prediabetes/Diabetes: Proportion of state that has ever had Prediabetes/Diabetes
  right_join(computedStatesHealth, by = "State")

# Risk Behavior Goes Here

computeBMI <- function(height, weight) {
  index = 1
  for(element in weight) {
    height[[index]] = (height[[index]] - (height[[index]] %% 100)) * (12 / 100) + (height[[index]] %% 100)
    weight[[index]] = 703 * element / (height[[index]] * height[[index]])
    index = index + 1
  }
  return(weight)
}

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(WEIGHT2 > 49) %>%
  filter(WEIGHT2 < 1000) %>% # ignores metric respondants
  filter(HEIGHT3 > 199) %>%
  filter(HEIGHT3 < 800) %>% # ignores metric respondants
  mutate(BMI = computeBMI(HEIGHT3, WEIGHT2)) %>%
  summarize(BMI = mean(BMI)) %>% # BMI: Average BMI of the state
  right_join(computedStatesHealth, by = "State")

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(SMOKE100 > 0) %>%
  filter(SMOKE100 < 3) %>%
  mutate(SMOKE100 = recodeBool(SMOKE100)) %>%
  summarize(Smoker = mean(SMOKE100)) %>% # 0-1; Smokers: Proportion of state that has ever smoked at least 100 cigarettes
  right_join(computedStatesHealth, by = "State")

recodeDrinks <- function(column) {
  index = 1
  for(element in column) {
    if(element == 88) {
      column[[index]] = 0
    }
    index = index + 1
  }
  return(column)
}

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(AVEDRNK2 > 0) %>%
  filter(AVEDRNK2 < 78) %>%
  mutate(AVEDRNK2 = recodeDrinks(AVEDRNK2)) %>%
  summarize(Average_Alcohol = mean(AVEDRNK2)) %>% # Alcohol Use: Average daily alcohol intake
  right_join(computedStatesHealth, by = "State")

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(MAXDRNKS > 0) %>%
  filter(MAXDRNKS < 78) %>%
  mutate(MAXDRNKS = recodeDrinks(MAXDRNKS)) %>%
  summarize(Maximum_Alcohol = mean(MAXDRNKS)) %>% # Alcohol Use: Average maximum single sitting alcohol intake
  right_join(computedStatesHealth, by = "State")

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(FLUSHOT6 > 0) %>%
  filter(FLUSHOT6 < 3) %>%
  mutate(FLUSHOT6 = recodeBool(FLUSHOT6)) %>%
  summarize(Flu_Shot = mean(FLUSHOT6)) %>% # 0-1; Vaccine: Proportion of state that was vaccinated against flu in past year
  right_join(computedStatesHealth, by = "State")

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(PNEUVAC4 > 0) %>%
  filter(PNEUVAC4 < 3) %>%
  mutate(PNEUVAC4 = recodeBool(PNEUVAC4)) %>%
  summarize(Pneumonia_Vaccine = mean(PNEUVAC4)) %>% # 0-1; Vaccine: Proportion of state that was ever vaccinated against pneumonia
  right_join(computedStatesHealth, by = "State")

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(SEATBELT > 0) %>%
  filter(SEATBELT < 6) %>%
  summarize(Seatbelt = mean(SEATBELT)) %>% # 1-5; Seatbelt: 1 Always, 5 Never
  right_join(computedStatesHealth, by = "State")

recodeDriving <- function(column) {
  index = 1
  for(element in column) {
    if(element > 76) {
      column[[index]] = 0
    }
    index = index + 1
  }
  return(column)
}

computedStatesHealth <- states_health %>%
  group_by(State) %>%
  filter(DRNKDRI2 > 0) %>%
  filter(DRNKDRI2 < 89) %>%
  mutate(DRNKDRI2 = recodeDriving(DRNKDRI2)) %>%
  summarize(Drunk_Driving = mean(DRNKDRI2)) %>% # Drunk Driving: Average times driven while drunk in past month
  right_join(computedStatesHealth, by = "State")

computedStatesHealth %>%
  right_join(read_csv("./output/States_info.csv"), by = "State") %>%
  select(-c(Trump, Clinton)) %>%
	write.table(file = "./output/States_data.csv", row.names = FALSE, sep = ",")
  
```

```{r stateToString, echo = FALSE}
# State code to state string function
stateToString <- function(column) {
  index = 1
  for(stateCode in column) {
    if(stateCode == "AL") {
      column[[index]] = "Alabama"
    } else if(stateCode == "AK") {
      column[[index]] = "Alaska"
    } else if(stateCode == "AZ") {
      column[[index]] = "Arizona"
    } else if(stateCode == "AR") {
      column[[index]] = "Arkansas"
    } else if(stateCode == "CA") {
      column[[index]] = "California"
    } else if(stateCode == "CO") {
      column[[index]] = "Colorado"
    } else if(stateCode == "CT") {
      column[[index]] = "Connecticut"
    } else if(stateCode == "DE") {
      column[[index]] = "Delaware"
    } else if(stateCode == "DC") {
      column[[index]] = "District of Columbia"
    } else if(stateCode == "FL") {
      column[[index]] = "Florida"
    } else if(stateCode == "GA") {
      column[[index]] = "Georgia"
    } else if(stateCode == "HI") {
      column[[index]] = "Hawaii"
    } else if(stateCode == "ID") {
      column[[index]] = "Idaho"
    } else if(stateCode == "IL") {
      column[[index]] = "Illinois"
    } else if(stateCode == "IN") {
      column[[index]] = "Indiana"
    } else if(stateCode == "IA") {
      column[[index]] = "Iowa"
    } else if(stateCode == "KS") {
      column[[index]] = "Kansas"
    } else if(stateCode == "KY") {
      column[[index]] = "Kentucky"
    } else if(stateCode == "LA") {
      column[[index]] = "Louisiana"
    } else if(stateCode == "ME") {
      column[[index]] = "Maine"
    } else if(stateCode == "MD") {
      column[[index]] = "Maryland"
    } else if(stateCode == "MA") {
      column[[index]] = "Massachusetts"
    } else if(stateCode == "MI") {
      column[[index]] = "Michigan"
    } else if(stateCode == "MN") {
      column[[index]] = "Minnesota"
    } else if(stateCode == "MS") {
      column[[index]] = "Mississippi"
    } else if(stateCode == "MO") {
      column[[index]] = "Missouri"
    } else if(stateCode == "MT") {
      column[[index]] = "Montana"
    } else if(stateCode == "NE") {
      column[[index]] = "Nebraska"
    } else if(stateCode == "NV") {
      column[[index]] = "Nevada"
    } else if(stateCode == "NH") {
      column[[index]] = "New Hampshire"
    } else if(stateCode == "NJ") {
      column[[index]] = "New Jersey"
    } else if(stateCode == "NM") {
      column[[index]] = "New Mexico"
    } else if(stateCode == "NY") {
      column[[index]] = "New York"
    } else if(stateCode == "NC") {
      column[[index]] = "North Carolina"
    } else if(stateCode == "ND") {
      column[[index]] = "North Dakota"
    } else if(stateCode == "OH") {
      column[[index]] = "Ohio"
    } else if(stateCode == "OK") {
      column[[index]] = "Oklahoma"
    } else if(stateCode == "OR") {
      column[[index]] = "Oregon"
    } else if(stateCode == "PA") {
      column[[index]] = "Pennsylvania"
    } else if(stateCode == "RI") {
      column[[index]] = "Rhode Island"
    } else if(stateCode == "SC") {
      column[[index]] = "South Carolina"
    } else if(stateCode == "SD") {
      column[[index]] = "South Dakota"
    } else if(stateCode == "TN") {
      column[[index]] = "Tennessee"
    } else if(stateCode == "TX") {
      column[[index]] = "Texas"
    } else if(stateCode == "UT") {
      column[[index]] = "Utah"
    } else if(stateCode == "VT") {
      column[[index]] = "Vermont"
    } else if(stateCode == "VA") {
      column[[index]] = "Virginia"
    } else if(stateCode == "WA") {
      column[[index]] = "Washington"
    } else if(stateCode == "WV") {
      column[[index]] = "West Virginia"
    } else if(stateCode == "WI") {
      column[[index]] = "Wisconsin"
    } else if(stateCode == "WY") {
      column[[index]] = "Wyoming"
    }
    index = index + 1
  }
  return(column)
}
```

```{r religionData, echo = FALSE, message = FALSE}
recodeNone <- function(religion) {
  index = 1
  for(element in religion) {
    if(element == 9 | element == 10 | element == 12) {
      religion[[index]] = 0
    } else if(element > 0 & element < 100) {
      religion[[index]] = 1
    } else {
      religion[[index]] = 2
    }
    index = index + 1
  }
  return(religion)
}

tibbie <- read_sav("./raw_data/Dataset - Pew Research Center 2014 Religious Landscape Study National Telephone Survey - Version 1.1 - December 1 2016.sav") %>%
  select(c(state, WEIGHT, qe1, qg1)) %>%
  rename(State = state, Religion = qe1, God = qg1, Weight = WEIGHT) %>%
  mutate(State = fipsTranslator(as.numeric(State))) %>%
  mutate(Religion = recodeNone(Religion)) %>%
  filter(!(Religion == 2)) %>%
  filter(God == 1 | God == 2) %>%
  mutate(God = recodeBool(God)) %>%
  group_by(State)

totalWeight <- tibbie %>%
  summarize(Total_Weight = sum(Weight)) %>%
  distinct()

totalReligionWeight <- tibbie %>%
  right_join(totalWeight) %>%
  mutate(Religion_Weight = Religion * Weight) %>%
  summarize(Total_Religion_Weight = sum(Religion_Weight)) %>%
  distinct()

totalGodWeight <- tibbie %>%
  right_join(totalWeight) %>%
  mutate(God_Weight = God * Weight) %>%
  summarize(Total_God_Weight = sum(God_Weight)) %>%
  distinct()

proportionNone <- totalReligionWeight %>%
  right_join(totalWeight) %>%
  transmute(State, Proportion_None = (Total_Weight - Total_Religion_Weight) / Total_Weight) # These values are off by +- 2% of the official cross tabs given by Pew, but clearly this roundabout way of weighting is "relatively" accurate

proportionNoGod <- totalGodWeight %>%
  right_join(totalWeight) %>%
  transmute(State, Proportion_NoGod = (Total_Weight - Total_God_Weight) / Total_Weight) # These values appear to be "exactly" the same as the official cross tabs. How the same procedure can exist in a quantum state of correctly and incorrectly weighting is left as an exercise to the reader.

read_csv("./output/States_info.csv") %>%
  right_join(proportionNone) %>%
  right_join(proportionNoGod) %>%
	write.table(file = "./output/States_info.csv", row.names = FALSE, sep = ",")
```

```{r confederateData, echo = FALSE, message = FALSE, warning = FALSE}
monuments <- read_csv("./raw_data/Whose Heritage SF - Symbol Type Count by State.csv") %>%
  slice(2:36) %>%
  select("COUNTA of feature_name", X14) %>%
  rename(State = "COUNTA of feature_name", Monuments = X14) %>%
  mutate(State = stateToString(State)) %>%
  group_by(State) %>%
  filter(!is.na(Monuments)) %>%
  mutate(Monuments = as.numeric(Monuments))

monuments$Monuments[[8]] = monuments$Monuments[[8]] + monuments$Monuments[[9]] # duplicate Georgia in dataset

pop <- read_csv("./output/States_COVID_data_by_date.csv") %>%
  select(c(State, Population)) %>%
  distinct()

zero <- function(column) {
  index = 1
  for(element in column) {
    if(is.na(element)) {
      column[[index]] = 0
    }
    index = index + 1
  }
  return(column)
}

monuments <- monuments %>%
  top_n(1, Monuments) %>%
  right_join(pop) %>%
  transmute(State, Per_Capita_Monuments = Monuments / Population) %>%
  mutate(Per_Capita_Monuments = zero(Per_Capita_Monuments))

read_csv("./output/States_info.csv") %>%
  mutate(State = stateToString(State)) %>%
  select(-c(Trump,Clinton)) %>%
  right_join(monuments) %>%
	write.table(file = "./output/States_info.csv", row.names = FALSE, sep = ",")
```

```{r wholeFoodsData, echo = FALSE, message = FALSE}
perCap <- read_csv("./raw_data/States-WholeFoods.csv") %>%
  mutate(State = stateToString(State)) %>%
  right_join(pop) %>%
  transmute(State, Per_Capita_Whole_Foods = Number_Whole_Foods / Population)

read_csv("./output/States_info.csv") %>%
  mutate(State = stateToString(State)) %>%
  right_join(perCap) %>%
	write.table(file = "./output/States_info.csv", row.names = FALSE, sep = ",")
```

```{r combineData, echo = FALSE, message = FALSE}
tibbs <- read_csv("./output/States_info.csv")

read_csv("./output/States_data.csv") %>%
  mutate(State = stateToString(State)) %>%
  right_join(tibbs) %>%
  write.table(file = "./output/States_total_info.csv", row.names = FALSE, sep = ",")
```

## Reference

1. China Data Lab, 2020, "US COVID-19 Daily Cases with Basemap", https://doi.org/10.7910/DVN/HIDLTK, Harvard Dataverse, V29, UNF:6:y1QAODHTEl8JQUjhLX6+Kw== [fileUNF]
1. Federal Election Commission
1. Wikipedia